import type { EPI, Movement } from "./types"

export const mockEPIs: EPI[] = [
  {
    id: "1",
    name: "Capacete de Segurança Branco",
    type: "Proteção da Cabeça",
    ca_number: "12345",
    manufacturer: "SafetyTech",
    ca_validity: "2025-12-31",
    status: "ativo",
    stock_quantity: 15,
    min_stock: 10,
    created_at: "2024-01-15",
    updated_at: "2024-01-15",
  },
  {
    id: "2",
    name: "Óculos de Proteção",
    type: "Proteção dos Olhos",
    ca_number: "67890",
    manufacturer: "VisionSafe",
    ca_validity: "2024-06-30",
    status: "ativo",
    stock_quantity: 5,
    min_stock: 8,
    created_at: "2024-01-10",
    updated_at: "2024-01-10",
  },
  {
    id: "3",
    name: "Luvas de Segurança",
    type: "Proteção das Mãos",
    ca_number: "11111",
    manufacturer: "HandProtect",
    ca_validity: "2025-03-15",
    status: "ativo",
    stock_quantity: 25,
    min_stock: 15,
    created_at: "2024-01-05",
    updated_at: "2024-01-05",
  },
  {
    id: "4",
    name: "Botina de Segurança",
    type: "Proteção dos Pés",
    ca_number: "22222",
    manufacturer: "FootSafe",
    ca_validity: "2024-02-28",
    status: "ativo",
    stock_quantity: 3,
    min_stock: 5,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "5",
    name: "Protetor Auricular",
    type: "Proteção Auditiva",
    ca_number: "33333",
    manufacturer: "SoundBlock",
    ca_validity: "2025-08-20",
    status: "inativo",
    stock_quantity: 0,
    min_stock: 10,
    created_at: "2023-12-20",
    updated_at: "2023-12-20",
  },
]

export const mockMovements: Movement[] = [
  {
    id: "1",
    epi_id: "1",
    epi_name: "Capacete de Segurança Branco",
    type: "entrega",
    quantity: 2,
    employee_name: "João Silva",
    employee_registration: "001",
    user_name: "Admin",
    movement_date: "2024-01-19",
    observation: "Entrega para obra setor A",
  },
  {
    id: "2",
    epi_id: "2",
    epi_name: "Óculos de Proteção",
    type: "devolucao",
    quantity: 1,
    employee_name: "Maria Santos",
    employee_registration: "002",
    user_name: "Admin",
    movement_date: "2024-01-18",
    observation: "Devolução após término do projeto",
  },
  {
    id: "3",
    epi_id: "3",
    epi_name: "Luvas de Segurança",
    type: "entrega",
    quantity: 5,
    employee_name: "Pedro Costa",
    employee_registration: "003",
    user_name: "Admin",
    movement_date: "2024-01-17",
    observation: "Entrega para equipe de manutenção",
  },
  {
    id: "4",
    epi_id: "4",
    epi_name: "Botina de Segurança",
    type: "manutencao",
    quantity: 1,
    employee_name: "Ana Oliveira",
    employee_registration: "004",
    user_name: "Admin",
    movement_date: "2024-01-16",
    observation: "Enviado para reparo do solado",
  },
]
